Auth/urls.py
from django.urls import path
from . import views
app_name = "Authentification"
urlpatterns = [
    path("signup",views.inscription,name = "signup"),
    path("signin",views.seconnecter,name="signin"),
    path("confirm", views.confirm, name="confirm"),
    path("disconnect",views.disconnect,name="disconnect"),
    path("recover",views.recoverPassword,name="recover"),
    path("delete",views.suprimerNotValid,name="delete"),
    path("change",views.changePassword,name="change")
]

Home/urls.py
from django.urls import path
app_name = "Home"
from . import views
urlpatterns = [
    path("",views.principale,name = "signup"),
    path("afficher",views.afficherProfil,name = "afficher"),
    path("impressum",views.impressum,name = "impressum"),
    path("essatials/allemagne",views.informationsgerman,name="germaninfo"),
    path("essatials/autriche",views.informationsgerman,name="autricheinfo"),
    path("essatials/",views.infos,name="info"),
    path("forum",views.forum,name="forum"),
    path("delete",views.delete,name="deletemessage"),
    path("edit",views.edit,name="edit"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("choice",views.zhome,name="zhome")
]

germanstudies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Auth/',include("Auth.urls",namespace="Authf"),name="Authentification"),
    url(r'^Horen/', include("Horen.urls",namespace="Horenf"),name="Horen"),
    url(r'^Lesen/', include("Lesen.urls",namespace="Lesenf"),name="Lesen"),
    url(r'^Schreiben/', include("Schreiben.urls",namespace="Schreibenf"),name="Schreiben"),
    url(r'^Grammar/', include("Grammar.urls",namespace="Grammarf"),name="Grammar"),
    url(r'^',include("Home.urls",namespace="Homef"),name="Session")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models
from Auth.models import Personne
# Create your models here.
from time import *
import threading
import Home.timer as timer
import threading


class Message(models.Model):

    message = models.TextField()
    subject = models.TextField()
    personne = models.ForeignKey(Personne,on_delete=models.CASCADE)
'''
def countup():
    i = 0
    global my_timer
    while(i==0):
        my_timer = 5

        for x in range(86400):
            sleep(1)
        messages = Message.objects.all()
        for message in messages:
            message.delete()

threadforum = threading.Thread(target=countup)
threadforum.start()
'''

Home/views.py
from django.shortcuts import render
from django.template import loader
from .models import Message
from Auth.models import  Personne
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from Home.funktions.funktion import getName
import hashlib
import Auth.ValidEntry.sender as sender
import Auth.ValidEntry.random as randomer
import Auth.ValidEntry.Validator as valid
from Schreiben.models import Reponse,Correction
import datetime
import Grammar.models as ayman
import Lesen.models as bouchakor
import Horen.models as yasser
from Home.funktions.funktion import checkSession
# Create your views here.

def principale(request):
    StringUser = request.session.get('username')
    if(StringUser == None or len(StringUser) == 0):
        template = loader.get_template("Home.html")
        return HttpResponse(template.render(request=request))
    else:
        succes_grammar = request.session['succes_lesen']
        succes_horen = request.session['succes_horen']
        succes_lesen = request.session['succes_lesen']
        ubungsayman = ayman.Ubung.objects.all()
        ubungsbouchakor = bouchakor.Ubung.objects.all()
        ubungsyasser = yasser.ModelTest.objects.all()
        total = int(succes_lesen + succes_horen + succes_grammar)
        context = {
            'total': total,
            'nbexo':len(ubungsayman) + len(ubungsbouchakor) + len(ubungsyasser)
        }
        return render(request, "session/session.html", context)

def afficherProfil(request):
    user = request.session['username']
    if(user == None or len(user) <= 0):
        return HttpResponseRedirect("/")
    else:
        context = {
            "personne":Personne.objects.get(username = request.session['username'])
        }
        return render(request,"afficher/profil.html",context)

def impressum(request):
    template = loader.get_template("impressum.html")
    return HttpResponse(template.render())
def informationsgerman(request):
    template = loader.get_template("Info/German.html")
    return HttpResponse(template.render())
def informationsautriche(request):
    template = loader.get_template("Info/Autriche.html")
    return HttpResponse(template.render())
def infos(request):
    try:
        id = request.POST['id']
        if(id == '1'):
            informationsgerman(request)
        elif(id == '2'):
            informationsautriche(request)
        else:
            return render(request,"Info/info.html")
    except:
        return render(request, "Info/info.html")
def forum(request):
    try:
        checkSession(request)
        if request.method=='GET':
            messages = Message.objects.all()
            paginator = Paginator(messages,5)
            idpage = request.GET.get('page')
            try:
                messagesG = paginator.page(idpage)
            except PageNotAnInteger:
                messagesG = paginator.page(1)
            except EmptyPage:
                messagesG = paginator.page(paginator.num_pages)
            context = {
                "messages":messagesG
            }
            return render(request,"forum/forum.html",context)
        else:
            attributs = request.POST
            words = open("Home/badword.txt","r",encoding="UTF-8")
            sujet = attributs['subject']
            message = attributs['message']
            erreur = ""
            checker = True
            for word in words.read().split("\n"):
                try:
                    message.index(word,0,len(message) - 1)
                    erreur = "Veuillez ne pas dire les gros mot"
                    checker = False
                except:
                    print("Ok")
                    pass
                try:
                    sujet.index(word.trim(),0,len(sujet))
                    checker = False
                except:
                    pass
            print(checker)
            if checker:
                    username = request.session['username']
                    personne = Personne.objects.get(username =  username)
                    messagess = Message(message = message,personne = personne,subject = sujet)
                    messagess.save()
                    messages = Message.objects.all()
                    paginator = Paginator(messages,5)
                    idpage = request.GET.get('page')
                    try:
                        messagesG = paginator.page(idpage)
                    except PageNotAnInteger:
                        messagesG = paginator.page(1)
                    except EmptyPage:
                        messagesG = paginator.page(paginator.num_pages)
                    context = {
                        "messages":messagesG
                    }
                    return render(request,"forum/forum.html",context)
            else:
                messages = Message.objects.all()
                paginator = Paginator(messages, 5)
                idpage = request.GET.get('page')
                try:
                    messagesG = paginator.page(idpage)
                except PageNotAnInteger:
                    messagesG = paginator.page(1)
                except EmptyPage:
                    messagesG = paginator.page(paginator.num_pages)
                context = {
                    "messages": messagesG,
                    "erreur": erreur
                }
                return render(request,"forum/forum.html",context)
    except IndexError:
            return HttpResponseRedirect("/")
def edit(request):
    try:
            checkSession(request)
            if request.method == "POST":
                action = request.POST.get('action')
                if action == 'delete':
                    personne = Personne.objects.get(username = request.session['username'])
                    message = Message.objects.filter(personne = personne)
                    ReponseHorens = yasser.ReponseHoren.objects.filter(personnes = personne)
                    GrammarReponse = ayman.Reponse.objects.filter(pers = personne)
                    LesenReponse = bouchakor.Reponse.objects.filter(pers = personne)
                    reponses = Reponse.objects.filter(personne = personne)
                    for rep in reponses:
                        corrections = Correction.objects.filter(reponse = rep)
                        for correction in corrections:
                            correction.delete()
                        rep.delete()
                    for mes in message:
                        mes.delete()
                    for rh in ReponseHorens:
                        rh.delete()
                    for gr in GrammarReponse:
                        gr.delete()
                    for lr in LesenReponse:
                        lr.delete()
                    personne.delete()
                    request.session.flush()
                    request.session.clear_expired()
                    return HttpResponseRedirect("/")
                elif action == 'changeemailfirst':
                    email = request.POST['email']
                    passw = request.POST['password']
                    cpassword = hashlib.md5(passw.encode())
                    personne = Personne.objects.get(username=request.session['username'])
                    context = {

                    }
                    if personne.password == cpassword.hexdigest():
                        personnes = Personne.objects.filter(email=email)
                        if len(personnes) == 0:
                            code = randomer.generateRandom()
                            request.session['code'] = code
                            request.session['nemail'] = email
                            info = {
                                "address":email,
                                "text":"Votre de code changement est " + code,
                                "subject": "Changer le code"
                            }
                            sender.sendEmail(info,request)
                            context['success'] = "Vrai"
                        else:
                            context['success'] = "Faux"
                            context["errorfirst"] = "Email dèja existant"
                    else:
                        context['success'] = "Faux"
                        context["errorfirst"] = "Mot de passe incorrect",
                    return JsonResponse(context)
                elif action == 'changemailsecond':
                    personne = Personne.objects.get(username = request.session['username'])
                    code = request.session['code']
                    codeR = request.POST.get('code')
                    context = {
                    }
                    if code == codeR:
                        personne = Personne.objects.get(email = request.session['email'])
                        personne.email = request.session['nemail']
                        personne.save()
                        context['success'] = "Vrai"
                    else:
                        context['errorfirst'] = "Le code est incorrect"
                    return JsonResponse(context)
                elif action == "changepassword":
                    personne = Personne.objects.get(username = request.session['username'])
                    normalpassword = request.POST['normalpassword']
                    newpassword = request.POST['newpassword']
                    cnewpassword = request.POST['cnewpassword']
                    context = {

                    }
                    if len(newpassword) >= 9:
                        if newpassword == cnewpassword:
                            encryptednewpassword = hashlib.md5(newpassword.encode()).hexdigest()
                            if hashlib.md5(normalpassword.encode()).hexdigest() == personne.password:
                                personne.password = encryptednewpassword

Home/templates/forum/forum.html
{% extends 'Ba.html'%}
    {% include 'icon.html'%}
    {% load static %}
    {% block besoin %}
    <link href="{% static 'forum/main.css'%}" rel="stylesheet">
    <link href="{% static 'forum/file.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'forum/file.css'%}"/>
    <script type="text/javascript" src="{% static 'forum/main.js'%}"></script>
    <script type="text/javascript" src="{% static 'forum/jquery.js'%}"></script>

    <script type="text/javascript" src="{% static 'forum/select2.js'%}"></script>
    <link href="{% static 'forum/select2.css'%}" rel="stylesheet">
    <link href="{% static 'forum/select2-bootstrap.css'%}" rel="stylesheet">

    {% endblock %}

{% block body %}
        <div id="content" class="content">

<section class="section-sm">
    <div id="forum" class="container frame">

<div id="yw0" class="list-view">
<div class="items">
{% for message in messages %}
<div class="forum-item" id="p997">
    <div class="row">
        <div class="hidden-xs col-sm-2">
            <div class="text-center">
            <img class="img-thumbnail" src="/media/{{message.personne.photo}}" alt="">        <p class="margin-top-xs">
        <b>{{message.personne.username}}</b><br>
    </p>
</div>        </div>
        <div class="col-xs-12 col-sm-10">
            <div class="row">
                <div class="col-xs-8">
                    <p>
                        <span class="visible-xs"><b>{{message.personne.prenom}}</b></span>
                        <span class="small">{{message.date}}</span>
                    </p>
                </div>

               {% if message.personne.username == request.session.username %}
                    <div class="col-xs-4">
                        <a style="text-decoration:none" style="color:white" href="{% url 'Home:deletemessage'%}?id={{message.id}}">delete</a>
                    </div>
                {% endif %}
            </div>

            <div class="forum-text bbcode">
                <p><strong style="font-size:19px">Sujet :</strong>  {{message.subject}} </p><br><div dir="ltr">{{message.message}}<br>                       </div>
                                    <p></p>
            </div>

        </div>
    </div>
</div>

{% endfor %}
</div>
<div class="writemessage">
<form method="post" action="{% url 'Home:forum'%}">
    {% csrf_token %}
    <div class="subjectcl">
        <label for="subject">Sujet </label>
        <input name="subject" value="" placeholder="Sujet" id = "subject"/>
    </div>
    <br><br>
    <div class="messagecl">
        <label for="message">Message </label>
        <input name="message" value="" placeholder="Message" id="message"/>
    </div>
    <p style="color:red">{{erreur}}</p>
    <div class="btn-sub">
        <button>Send</button>
    </div>
</form>
</div>
<nav class="text-center content-item"><div class="pagination"><ul id="yw11" class="yiiPager">
    {% if messages.has_previous %}
        <li class="previous"><a href="{% url 'Home:forum'%}?page={{messages.previous_page_number}}">&lt;</a></li>
    {% endif %}
    {% if messages.has_next%}
        <li class="next"><a href="{% url 'Home:forum'%}?page={{messages.next_page_number}}">&gt;</a></li>
    {% endif %}

</ul></div></nav><div class="keys" style="display:none" title="/fr/forum/topic/275"><span>997</span><span>1012</span><span>1041</span><span>1895</span><span>1906</span><span>5313</span><span>5538</span><span>5562</span><span>8350</span><span>8694</span></div>
</div>    </div>
</section>


        </div><!-- content -->
{% endblock %}