Auth/urls.py
from django.urls import path
from . import views
app_name = "Authentification"
urlpatterns = [
    path("signup",views.inscription,name = "signup"),
    path("signin",views.seconnecter,name="signin"),
    path("confirm", views.confirm, name="confirm"),
    path("disconnect",views.disconnect,name="disconnect"),
    path("recover",views.recoverPassword,name="recover"),
    path("delete",views.suprimerNotValid,name="delete"),
    path("change",views.changePassword,name="change")
]

Schreiben/urls.py
app_name = "Schreiben"
from django.urls import path
from . import views
urlpatterns = [
    path("",views.index,name="homeschreiben"),
    path("correction",views.correction,name="correction")
]

germanstudies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Auth/',include("Auth.urls",namespace="Authf"),name="Authentification"),
    url(r'^Horen/', include("Horen.urls",namespace="Horenf"),name="Horen"),
    url(r'^Lesen/', include("Lesen.urls",namespace="Lesenf"),name="Lesen"),
    url(r'^Schreiben/', include("Schreiben.urls",namespace="Schreibenf"),name="Schreiben"),
    url(r'^Grammar/', include("Grammar.urls",namespace="Grammarf"),name="Grammar"),
    url(r'^',include("Home.urls",namespace="Homef"),name="Session")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Schreiben/models.py
from django.db import models
from Auth.models import Personne


class Excercice(models.Model):
    text = models.TextField(blank=True)
    sujet = models.CharField(max_length=50)


class Reponse(models.Model):
    rep = models.TextField(blank=True, null=True)
    legal = models.BooleanField(default=False)
    corrected = models.BooleanField(default=False)
    excercice = models.ForeignKey(Excercice, on_delete=models.CASCADE)
    personne = models.ForeignKey(Personne, on_delete=models.CASCADE)
class Correction(models.Model):
    text = models.TextField()
    remarque = models.TextField()
    reponse = models.OneToOneField(Reponse,on_delete=models.CASCADE,null=True)

Schreiben/views.py
from django.shortcuts import render
from Schreiben.Fonctions import piocher as pioche
from django.http import HttpResponseRedirect
from Home.funktions.funktion import checkSession
from .models import Excercice,Reponse,Personne,Correction
from Auth.ValidEntry.sender import sendEmail
# Create your views here.

def index(request):
    try:
        checkSession(request)
        if request.method == "GET":
            try:
                exercice = pioche.getSchreiben(request)
            except:
                context = {
                    "error": "Nous nous somme désolé , nous avons pas encore d'excercices de schreiben"
                }
                return render(request, "errorpagesession.html", context)
            context = {
                "exercice":exercice
            }
            return render(request,"index.html",context)
        else:
            text = request.POST['schreiben']
            id = request.POST['id']
            reponse = Reponse(rep=text,personne = Personne.objects.get(username = request.session['username']),excercice = Excercice.objects.get(id=int(id)))
            reponse.save()
            personneactuel = Personne.objects.get(username = request.session['username'])
            reponsesa = Reponse.objects.filter(corrected = False)
            reponses = [
            ]
            for rek in reponsesa:
                if rek.personne != personneactuel:
                    reponses.append(rek)
            list = []
            for rep in reponses:
                if reponse != rep:
                    list.append(rep)
            try:
                list[0]
            except:
                reponse.legal = True
                reponse.save()
                context = {
                    "error": "Nous nous sommes désolé , nous ne avons pas autre client pour que vous corrigé"
                }
                return render(request, "errorpagesession.html", context)
            context = {
                "reponse":list[0],
                "reponseperso":reponse
            }
            return render(request,"reponse.html",context)
    except IndexError:
        return HttpResponseRedirect("/")
def correction(request):
            checkSession(request)
            if request.method == "POST":
                textcorr = request.POST['correction']
                remarque = request.POST['remarque']
                idperso = request.POST['idperso']
                reponse = Reponse.objects.get(id=int(idperso))
                etrresponse = Reponse.objects.get(id=int(request.POST['id']))
                if len(textcorr) < 20 or len(remarque) < 10:
                    context = {
                        "error":"Les champs ne respectent pas les condition",
                        "reponseperso":reponse,
                        "reponse": etrresponse
                    }
                    return render(request,"reponse.html",context)
                else:
                    reponse.legal = True
                    reponse.save()
                    etrresponse.corrected= True
                    etrresponse.save()
                    if reponse.corrected:
                        correction = Correction.objects.get(reponse = reponse)
                        info = {
                            "address" : reponse.personne.email,
                            "text": correction.text +'\n Remarques \n' + correction.remarque,
                            "subject":"Correction d'excercice" + correction.reponse.excercice.sujet
                        }
                        sendEmail(info,request)

                    if etrresponse.legal:
                        correction1 = Correction(text = textcorr,remarque = remarque,reponse = etrresponse)
                        info = {
                            "address": etrresponse.personne.email,
                            "text": correction1.text + '\n Remarques \n' + correction1.remarque,
                            "subject": "Correction d'excercice" + correction1.reponse.excercice.sujet
                        }
                        sendEmail(info,request)
                    context = {
                        "keyword":"success",
                        "success":"Votre corrigé a été bien reçu, vous allez reçevoir votre correction sur votre email"
                    }
                    return render(request,"success.html",context)
            else:
                context = {
                    "keyword": "error",
                    "error": "n'essaye pas de pirater"
                }
                return render(request,"errorpagesession.html",context)

Schreiben/templates/index.html
{% extends 'Ba.html'%}
{% load static %}
{% block besoin %}
    <link href="{% static 'css/style.css'%}" rel="stylesheet"/>
{% endblock %}
{% block body %}
<section>
    <div class="redemittel">
        <div class="redemittel-image">
            <img src="{% static 'schreiben.jpg'%}" alt=""/>
        </div>
        <div class="redemittelb">
            <div class="redemittel-titre">
                <p>Redemittel</p>
            </div>
            <div class="redemittel-body">
                <a href="/media/pdf/redemittel.pdf"><p>Redemiitel</p></a>
                <a href="/media/pdf/w1.pdf"><p>Wortschatz-1</p></a>
                <a href="/media/pdf/w2.pdf"><p>Wortschatz-2</p></a>
                <a href="/media/pdf/w3.pdf"><p>komminikation</p></a>
            </div>
        </div>

    </div>
    <div class="contenu">
        <div class="schreiben-enonce">
            <div class="schreiben">
                <div class="schreiben-sujet">
                    <p2>Théma : {{exercice.sujet}} </p2>
                </div>
                <div class="schreiben-text">
                    <p>{{exercice.text}}</p>
                </div>
            </div>
        </div>
        <br><br><br>
        <div class="schreiben-reponse">
            <form action="{% url 'Schreiben:homeschreiben'%}" method="post">
                {% csrf_token %}
                <input name="id" value="{{exercice.id}}" type="hidden"/>

                <textarea id="schreiben" name="schreiben" value="" placeholder="Gebe deine schreiben hier" maxlength="500 wörter"></textarea>
                <br><br>
                <div class="btn-submit">
                    <input type="submit" value="Senden">
                </div>
            </form>

        </div>
    </div>
</section>
{% endblock %}

Schreiben/templates/reponse.html
{% extends 'Ba.html'%}
{% load static %}
{% block besoin %}
    <link href="{% static 'css/style1.css'%}" rel="stylesheet"/>
{% endblock %}
{% block body %}
<section>
    <div class="premiersection">
            <h1>Correction</h1>
            <form method="post" action="{% url 'Schreiben:correction'%}">
                {% csrf_token %}
                <div class="">
                    <input name="id" value="{{reponse.id}}" type="hidden"/>
                    <input name="idperso" value="{{reponseperso.id}}" type="hidden"/>

                    <div class="correction-input">
                        <label for="corr">Correction</label>
                        <textarea id = "corr" class="text-area" name="correction"></textarea>
                    </div>
                    <div class="correction-input">
                        <label for="remarque">Remarque</label>
                        <textarea class="text-area" name="remarque" id="remarque"></textarea>
                    </div>
                    <div class="btn-submit">
                        <input value="senden" type="submit"/>
                    </div>
                    <p style="color:red" style="text-align:center">{{error}}</p>
                </div>
            </form>

    </div>
    <br><br>
    <div class="deusiemesection">
            <div class="schreiben-enonce">
                <div class="schreiben">
                    <div class="schreiben-sujet">
                        <p2>Théma ist " {{reponse.excercice.sujet}} " </p2>
                    </div>
                    <div class="schreiben-text">
                                    <p>{{reponse.excercice.text}}</p>
                    </div>
            </div><div class="schreiben-reponse">
                        <p3>{{reponse.rep}} </p3>
                                </div>

    </div>



</section>
{% endblock %}