Auth/urls.py
from django.urls import path
from . import views
app_name = "Authentification"
urlpatterns = [
    path("signup",views.inscription,name = "signup"),
    path("signin",views.seconnecter,name="signin"),
    path("confirm", views.confirm, name="confirm"),
    path("disconnect",views.disconnect,name="disconnect"),
    path("recover",views.recoverPassword,name="recover"),
    path("delete",views.suprimerNotValid,name="delete"),
    path("change",views.changePassword,name="change")
]

Home/urls.py
from django.urls import path
app_name = "Home"
from . import views
urlpatterns = [
    path("",views.principale,name = "signup"),
    path("afficher",views.afficherProfil,name = "afficher"),
    path("impressum",views.impressum,name = "impressum"),
    path("essatials/allemagne",views.informationsgerman,name="germaninfo"),
    path("essatials/autriche",views.informationsgerman,name="autricheinfo"),
    path("essatials/",views.infos,name="info"),
    path("forum",views.forum,name="forum"),
    path("delete",views.delete,name="deletemessage"),
    path("edit",views.edit,name="edit"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("choice",views.zhome,name="zhome")
]

germanstudies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Auth/',include("Auth.urls",namespace="Authf"),name="Authentification"),
    url(r'^Horen/', include("Horen.urls",namespace="Horenf"),name="Horen"),
    url(r'^Lesen/', include("Lesen.urls",namespace="Lesenf"),name="Lesen"),
    url(r'^Schreiben/', include("Schreiben.urls",namespace="Schreibenf"),name="Schreiben"),
    url(r'^Grammar/', include("Grammar.urls",namespace="Grammarf"),name="Grammar"),
    url(r'^',include("Home.urls",namespace="Homef"),name="Session")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models
from Auth.models import Personne
# Create your models here.
from time import *
import threading
import Home.timer as timer
import threading


class Message(models.Model):

    message = models.TextField()
    subject = models.TextField()
    personne = models.ForeignKey(Personne,on_delete=models.CASCADE)
'''
def countup():
    i = 0
    global my_timer
    while(i==0):
        my_timer = 5

        for x in range(86400):
            sleep(1)
        messages = Message.objects.all()
        for message in messages:
            message.delete()

threadforum = threading.Thread(target=countup)
threadforum.start()
'''

Home/views.py
from django.shortcuts import render
from django.template import loader
from .models import Message
from Auth.models import  Personne
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from Home.funktions.funktion import getName
import hashlib
import Auth.ValidEntry.sender as sender
import Auth.ValidEntry.random as randomer
import Auth.ValidEntry.Validator as valid
from Schreiben.models import Reponse,Correction
import datetime
import Grammar.models as ayman
import Lesen.models as bouchakor
import Horen.models as yasser
from Home.funktions.funktion import checkSession
# Create your views here.

def principale(request):
    StringUser = request.session.get('username')
    if(StringUser == None or len(StringUser) == 0):
        template = loader.get_template("Home.html")
        return HttpResponse(template.render(request=request))
    else:
        succes_grammar = request.session['succes_lesen']
        succes_horen = request.session['succes_horen']
        succes_lesen = request.session['succes_lesen']
        ubungsayman = ayman.Ubung.objects.all()
        ubungsbouchakor = bouchakor.Ubung.objects.all()
        ubungsyasser = yasser.ModelTest.objects.all()
        total = int(succes_lesen + succes_horen + succes_grammar)
        context = {
            'total': total,
            'nbexo':len(ubungsayman) + len(ubungsbouchakor) + len(ubungsyasser)
        }
        return render(request, "session/session.html", context)

def afficherProfil(request):
    user = request.session['username']
    if(user == None or len(user) <= 0):
        return HttpResponseRedirect("/")
    else:
        context = {
            "personne":Personne.objects.get(username = request.session['username'])
        }
        return render(request,"afficher/profil.html",context)

def impressum(request):
    template = loader.get_template("impressum.html")
    return HttpResponse(template.render())
def informationsgerman(request):
    template = loader.get_template("Info/German.html")
    return HttpResponse(template.render())
def informationsautriche(request):
    template = loader.get_template("Info/Autriche.html")
    return HttpResponse(template.render())
def infos(request):
    try:
        id = request.POST['id']
        if(id == '1'):
            informationsgerman(request)
        elif(id == '2'):
            informationsautriche(request)
        else:
            return render(request,"Info/info.html")
    except:
        return render(request, "Info/info.html")
def forum(request):
    try:
        checkSession(request)
        if request.method=='GET':
            messages = Message.objects.all()
            paginator = Paginator(messages,5)
            idpage = request.GET.get('page')
            try:
                messagesG = paginator.page(idpage)
            except PageNotAnInteger:
                messagesG = paginator.page(1)
            except EmptyPage:
                messagesG = paginator.page(paginator.num_pages)
            context = {
                "messages":messagesG
            }
            return render(request,"forum/forum.html",context)
        else:
            attributs = request.POST
            words = open("Home/badword.txt","r",encoding="UTF-8")
            sujet = attributs['subject']
            message = attributs['message']
            erreur = ""
            checker = True
            for word in words.read().split("\n"):
                try:
                    message.index(word,0,len(message) - 1)
                    erreur = "Veuillez ne pas dire les gros mot"
                    checker = False
                except:
                    print("Ok")
                    pass
                try:
                    sujet.index(word.trim(),0,len(sujet))
                    checker = False
                except:
                    pass
            print(checker)
            if checker:
                    username = request.session['username']
                    personne = Personne.objects.get(username =  username)
                    messagess = Message(message = message,personne = personne,subject = sujet)
                    messagess.save()
                    messages = Message.objects.all()
                    paginator = Paginator(messages,5)
                    idpage = request.GET.get('page')
                    try:
                        messagesG = paginator.page(idpage)
                    except PageNotAnInteger:
                        messagesG = paginator.page(1)
                    except EmptyPage:
                        messagesG = paginator.page(paginator.num_pages)
                    context = {
                        "messages":messagesG
                    }
                    return render(request,"forum/forum.html",context)
            else:
                messages = Message.objects.all()
                paginator = Paginator(messages, 5)
                idpage = request.GET.get('page')
                try:
                    messagesG = paginator.page(idpage)
                except PageNotAnInteger:
                    messagesG = paginator.page(1)
                except EmptyPage:
                    messagesG = paginator.page(paginator.num_pages)
                context = {
                    "messages": messagesG,
                    "erreur": erreur
                }
                return render(request,"forum/forum.html",context)
    except IndexError:
            return HttpResponseRedirect("/")
def edit(request):
    try:
            checkSession(request)
            if request.method == "POST":
                action = request.POST.get('action')
                if action == 'delete':
                    personne = Personne.objects.get(username = request.session['username'])
                    message = Message.objects.filter(personne = personne)
                    ReponseHorens = yasser.ReponseHoren.objects.filter(personnes = personne)
                    GrammarReponse = ayman.Reponse.objects.filter(pers = personne)
                    LesenReponse = bouchakor.Reponse.objects.filter(pers = personne)
                    reponses = Reponse.objects.filter(personne = personne)
                    for rep in reponses:
                        corrections = Correction.objects.filter(reponse = rep)
                        for correction in corrections:
                            correction.delete()
                        rep.delete()
                    for mes in message:
                        mes.delete()
                    for rh in ReponseHorens:
                        rh.delete()
                    for gr in GrammarReponse:
                        gr.delete()
                    for lr in LesenReponse:
                        lr.delete()
                    personne.delete()
                    request.session.flush()
                    request.session.clear_expired()
                    return HttpResponseRedirect("/")
                elif action == 'changeemailfirst':
                    email = request.POST['email']
                    passw = request.POST['password']
                    cpassword = hashlib.md5(passw.encode())
                    personne = Personne.objects.get(username=request.session['username'])
                    context = {

                    }
                    if personne.password == cpassword.hexdigest():
                        personnes = Personne.objects.filter(email=email)
                        if len(personnes) == 0:
                            code = randomer.generateRandom()
                            request.session['code'] = code
                            request.session['nemail'] = email
                            info = {
                                "address":email,
                                "text":"Votre de code changement est " + code,
                                "subject": "Changer le code"
                            }
                            sender.sendEmail(info,request)
                            context['success'] = "Vrai"
                        else:
                            context['success'] = "Faux"
                            context["errorfirst"] = "Email dèja existant"
                    else:
                        context['success'] = "Faux"
                        context["errorfirst"] = "Mot de passe incorrect",
                    return JsonResponse(context)
                elif action == 'changemailsecond':
                    personne = Personne.objects.get(username = request.session['username'])
                    code = request.session['code']
                    codeR = request.POST.get('code')
                    context = {
                    }
                    if code == codeR:
                        personne = Personne.objects.get(email = request.session['email'])
                        personne.email = request.session['nemail']
                        personne.save()
                        context['success'] = "Vrai"
                    else:
                        context['errorfirst'] = "Le code est incorrect"
                    return JsonResponse(context)
                elif action == "changepassword":
                    personne = Personne.objects.get(username = request.session['username'])
                    normalpassword = request.POST['normalpassword']
                    newpassword = request.POST['newpassword']
                    cnewpassword = request.POST['cnewpassword']
                    context = {

                    }
                    if len(newpassword) >= 9:
                        if newpassword == cnewpassword:
                            encryptednewpassword = hashlib.md5(newpassword.encode()).hexdigest()
                            if hashlib.md5(normalpassword.encode()).hexdigest() == personne.password:
                                personne.password = encryptednewpassword

Home/templates/Ba.html
<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    {% load static %}
    <meta charset="utf-8">
    {% include 'icon.html'%}

    <link href="{% static 'session_fichiers/bootstrap.css'%}" rel="stylesheet">
    <link href="{% static 'session_fichiers/main.css'%}" rel="stylesheet">
    <script src="{% static 'session_fichiers/jquery-2.js'%}"></script>
    <script src="{% static 'session_fichiers/jquery-ui.js'%}"></script>
    <script src="{% static 'session_fichiers/jquery_002.js'%}"></script>
    <script src="{% static 'session_fichiers/bootstrap.js'%}"></script>

    <script type="text/javascript" src="{% static 'session_fichiers/jquery.js'%}"></script>

    <script type="text/javascript" src="{% static 'session_fichiers/select2.js'%}"></script>
    <link href="{% static 'session_fichiers/select2.css'%}" rel="stylesheet">
    <link href="{% static 'session_fichiers/select2-bootstrap.css'%}" rel="stylesheet">
    {% block besoin %}
    <title>Cours - deutsch lernen</title>
    {%endblock %}
</head>

<body class="translation">


<div id="wrapper" class="internal">
            <a class="sr-only sr-only-focusable" href="#content">Aller au contenu</a>
<nav class="toolbar fixed affix-top" data-spy="affix" data-offset="90">
    <div class="container-fluid">
        <ul class="nav" id="yw0">
<li><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#"><span class="visible-xs-inline"><img class="" src="{% static 'session_fichiers/user_25_25.jpg'%}" alt=""></span><span class="hidden-xs">{{request.session.username}}</span><span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="/afficher">Afficher le profil</a></li>
    <li class="divider"><span></span></li>
<li><a href="{% url 'Home:edit'%}">Préferences</a></li>
<li class="divider"><span></span></li>
<li><a href="/Auth/disconnect">Déconnexion</a></li>
</ul>
</li>
<li><a data-toggle="tooltip" data-html="true" title="Clavier (Alt+2)&lt;div class=&quot;big&quot; dir=&quot;ltr&quot;&gt;ae → ä, oe → ë,&lt;br&gt;ue → ü, ss → ß&lt;/div&gt;" data-placement="bottom" href="javascript:void(0);"><span id="keyboard-button" class="icon svg-sprite svg keyboard active"><svg xmlns="http://www.w3.org/2000/svg" id="icon-keyboard" viewBox="0 0 39 21"><path d="M13.5 15.8v-4.5c0-1.7-.2-2.9-.5-3.5-.4-.6-1-1.2-1.9-1.6-.9-.4-2.2-.6-4-.6-2 0-3.5.3-4.5 1S.9 8.3.5 9.8l3.7.6c.2-.7.6-1.2 1-1.4.4-.3 1-.4 1.7-.4 1.1 0 1.8.2 2.2.5.4.3.6.9.6 1.6v.4c-.7.3-2 .6-3.9 1-1.4.3-2.5.6-3.2.9-.7.3-1.3.8-1.7 1.5-.7.6-.9 1.3-.9 2.1 0 1.3.5 2.3 1.4 3.1.9.9 2.1 1.3 3.7 1.3.9 0 1.7-.2 2.5-.5s1.5-.8 2.2-1.5c0 .1.1.2.1.5.2.5.3.9.4 1.2h4c-.4-.7-.6-1.4-.7-2-.1-.6-.1-1.6-.1-2.9zm-4-1.4c0 .9-.1 1.6-.2 1.9-.2.5-.5.9-1 1.3-.6.4-1.3.7-2 .7s-1.2-.2-1.6-.6c-.4-.4-.6-.9-.6-1.4 0-.6.3-1 .8-1.4.3-.2 1.1-.4 2.2-.7 1.1-.2 1.9-.4 2.4-.6v.8zM33.2 0h3.5v3.3h-3.5zM27 0h3.5v3.3H27zm11.3 18.7c-.1-.6-.2-1.6-.2-2.9v-4.5c0-1.7-.2-2.9-.5-3.5-.4-.6-1-1.2-1.9-1.6-.9-.4-2.2-.6-4-.6-2 0-3.5.3-4.5 1s-1.7 1.7-2.1 3.2l3.7.6c.2-.7.6-1.2 1-1.4.4-.3 1-.4 1.7-.4 1.1 0 1.8.2 2.2.5.4.3.6.9.6 1.6v.4c-.7.3-2 .6-3.9 1-1.4.3-2.5.6-3.2.9-.7.3-1.3.8-1.7 1.5-.4.7-.6 1.4-.6 2.2 0 1.3.5 2.3 1.4 3.1.9.8 2.2 1.2 3.7 1.2.9 0 1.7-.2 2.5-.5s1.5-.8 2.2-1.5c0 .1.1.2.1.5.2.5.3.9.4 1.2h4c-.6-.7-.8-1.4-.9-2zm-4.2-4.3c0 .9-.1 1.6-.2 1.9-.2.5-.5.9-1 1.3-.7.5-1.4.7-2.1.7-.7 0-1.2-.2-1.6-.6-.4-.4-.6-.9-.6-1.4 0-.6.3-1 .8-1.4.3-.2 1.1-.4 2.2-.7 1.1-.2 1.9-.4 2.5-.6v.8z"></path><path fill="currentColor" d="M21.9 14.1l-5.2-2.8V17z"></path></svg></span></a></li>
</ul>    </div><!-- /.container-fluid -->
</nav>

<header id="header">
    <nav class="menu navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_menu" aria-expanded="false">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="/"><img class="logo icon svg-sprite svg" src="{% static 'session_fichiers/logo.png'%}" style="width:250px;height:60px;"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="main_menu">
                <ul class="nav navbar-nav navbar-right" id="yw1">
<li><a href="/">Level</a></li>
<li><a href="/Horen">Hören</a></li>
<li><a href="/Lesen">Lesen</a></li>
<li><a href="/Schreiben">Schreiben</a></li>
<li><a href="/Grammar">Grammar</a></li>
<li><a href="/forum">Forum</a></li>
<li><a href="/aboutus">About us</a></li>
<!--<li><a href="/forum">Forum</a></li>-->
</ul>            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</header>
    <div context="contexte">
        {% block body %}
        {% endblock %}
    </div>
    {% include 'footer.html'%}


</div></body></html>

Home/templates/Home.html
<!DOCTYPE html>
<!-- saved from url=(0023)https://deutsch.info/fr -->
<html dir="ltr" lang="fr" class=" svg"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% include 'icon.html'%}
    <meta name="theme-color" content="#ffffff">

    <link href="{% static 'Home_files/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'Home_files/main.min.css'%}" rel="stylesheet">
    <script src="{% static 'Home_files/jquery-2.1.1.min.js.download'%}"></script>
    <script src="{% static 'Home_files/jquery-ui.min.js.download'%}"></script>
    <script src="{% static 'Home_files/jquery.jplayer.min.js.download'%}"></script>
    <script src="{% static 'Home_files/bootstrap.min.js.download'%}"></script>
            <link rel="stylesheet" type="text/css" href="{% static 'Home_files/cookieconsent.min.css'%}">

    <title>Apprenez l’allemand gratuitement sur Internet - deutsch lernen</title>

<style></style></head>

<body class="translation">
<div id="wrapper" class="main">

    {% include 'header.html'%}
    <div class="content">
        
<section class="section section-intro">
    <div class="section-intro-content">
        <div class="container frame">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h1><span>Site multilangue</span> pour apprendre l’allemand</h1>
                        <p class="big text-white">Sur deutsch lernen, vous pouvez apprendre l’allemand partout, tout le temps et gratuitement, et tout cela en ligne et en plusieurs langues ! En plus de cours, d’explications sur la grammaire, de jeux et de supports audiovisuels, vous trouverez aussi des informations des informations pratiques pour vivre et travailler en Allemagne ou en Autriche ainsi que des supports pédagogiques gratuits.</p>
                                                <p><a class="btn btn-lg btn-white margin-top-md" href="{% url 'Authentification:signup'%}">Inscrivez-vous gratuitement !</a></p>
                                            </div>

                </div>
            </div>
        </div>
    </div>
</section>

<section class="section section-white section-md text-center">
    <div class="container frame">
        <h2 class="gray">Que peut-on y trouver ?</h2>
        <div class="triangle"></div>
    </div>
</section>


<section class="section section-content section-np text-center">
    <div class="container-fluid equal-height">
        <div class="row">
            <div class="col-sm-6 col-md-3 ng h content-block-1 courses" style="height: 339px;">
                <a href="/Auth/signin"><div class="icon svg-sprite svg"><svg xmlns="http://www.w3.org/2000/svg" id="icon-courses" viewBox="0 0 150 108"><path d="M75 75.32l43.898-19.258v22.89L75 98.25 31.1 78.953v-22.89L75 75.318zM19.395 53.015l10.554-6.984L75 65.796l75-32.9L75 0 0 32.896l17.256 7.57-6.96 4.606C8.666 46.15 7.69 47.96 7.69 49.907v17.427L1.836 84.762V108L13.54 96.525 25.25 107.98V84.76l-5.854-17.426V53.016z"></path></svg></div><h3>Cours</h3><p>Quatre cours complets de niveaux A1, A2, B1 et B2 avec des exercices interactifs et des supports audiovisuels</p></a>            </div>
            <div class="col-sm-6 col-md-3 ng h content-block-2 grammar" style="height: 339px;">
                <a href="/Auth/signin"><div class="icon svg-sprite svg"><svg xmlns="http://www.w3.org/2000/svg" id="icon-grammar" viewBox="0 0 130 100"><g><path d="M107.118 97.973v5.91H69.79v-5.91c6.708 0 8.968-6.883 7.155-11.787-1.322-3.6-7.373-19.81-7.373-19.81H34.578s-5.14 12.986-8.22 20.958c-3.08 7.974 4.137 10.64 10.772 10.64v5.91H4.47v-5.91s5.03-2.14 7.503-4.596c2.473-2.46 4.626-6.69 4.626-6.69L52.35-3.116h8.334l34.45 89.037s1.796 4.5 5.373 8.25c3.58 3.753 6.61 3.803 6.61 3.803m-39.74-40.61L52.913 16.61 36.92 57.363h30.456zM113.873 18.083s8.247-2.322 8.247-9.51c0-7.21-6.547-11.69-12.094-11.69H89.764V-.48c3.698.867 3.698 1.438 3.698 4.222V34.25c0 2.083-1.848 3.298-3.698 3.593v3.283h20.19c5.73 0 14.516-3.34 14.516-11.283 0-9.217-10.597-11.76-10.597-11.76m-11.165-15.67h5.47c3.7 0 4.81 3.244 4.81 6.45 0 3.192-1.11 6.455-4.81 6.455h-5.47V2.413zm5.527 33.18h-5.527V20.85h5.47c4.68 0 6.785 3.677 6.785 8.007 0 4.315-2.625 6.737-6.728 6.737"></path></g></svg></div><h3>Grammaire</h3><p>Les règles les plus importantes de la grammaire allemande illustrées par des exemples</p></a>            </div>
            <div class="col-sm-6 col-md-3 ng h content-block-3 library" style="height: 339px;">
                <a href="{% url 'Home:forum'%}"><div class="icon svg-sprite svg"><svg xmlns="http://www.w3.org/2000/svg" id="icon-library" viewBox="0 0 110 107"><path d="M29.21 68.333s2.292 6.794 2.292 18.178-2.292 18.214-2.292 18.214c0 1.253-1.03 2.276-2.292 2.276H15.326c-1.262 0-1.576-1.023-1.576-2.276V68.37c0-1.253.313-2.35 1.576-2.35H26.92c1.26 0 2.29 1.06 2.29 2.313m65.465-2.312H83.082c-1.263 0-2.292 1.06-2.292 2.313 0 0-2.29 6.776-2.29 18.16 0 11.383 2.29 18.222 2.29 18.222 0 1.253 1.03 2.285 2.292 2.285h11.593c1.262 0 1.574-1.023 1.574-2.276V68.37c0-1.253-.313-2.35-1.575-2.35M55 0C25.938 0 0 25.768 0 54.638v27.318c0 1.255 1.03 2.277 2.292 2.277h4.583c1.262 0 2.292-1.022 2.292-2.277V54.638C9.167 30.786 30.99 13.66 55 13.66s45.833 17.126 45.833 40.98v27.317c0 1.255 1.03 2.277 2.292 2.277h4.583c1.263 0 2.292-1.022 2.292-2.277v-27.32C110 25.768 84.06 0 55 0"></path></svg></div><h3>Forum</h3><p>Contenu social:Vous allez pouvoir poster des questions sur la langue allemande</p></a>            </div>
            <div class="col-sm-6 col-md-3 ng h content-block-6 info" style="height: 353px;">
                <a href="{% url 'Home:info'%}"><div class="icon svg-sprite svg"><svg xmlns="http://www.w3.org/2000/svg" id="icon-info" viewBox="0 0 118 118"><path d="M59 0C26.4 0 0 26.4 0 59s26.4 59 59 59 59-26.4 59-59S91.6 0 59 0M48.8 20.7c0-1.4 1-2.6 2.5-2.6h15.4c1.4 0 2.5 1.3 2.5 2.7V36c0 1.4-1 2.6-2.5 2.6H51.3c-1.4 0-2.5-1.2-2.5-2.6V20.7zM79.4 87c0 1.5-1 2.7-2.5 2.7H41c-1.3 0-2.4-1.2-2.4-2.6v-5c0-1.4 1-2.6 2.5-2.6H49V59H41c-1.3 0-2.4-1.2-2.4-2.6v-5c0-1.5 1-2.6 2.5-2.6h25.7c1.4 0 2.5 1 2.5 2.5v28H77c1.3 0 2.4 1.3 2.4 2.7v5z"></path></svg></div><h3>Informations utiles</h3><p>Des informations pratiques sur la vie en Allemagne et en Autriche, particulièrement utiles pour les migrants</p></a>            </div>
        </div>
    </div>
</section>

<section class="section section-white text-center">
    <div class="container frame">
        <div class="box quote">
    <h2>Le saviez-vous ?</h2>
    <blockquote>
        <p>Johann Christoph Adelung fur un lexicographe et germaniste allemand. Son livre de 1774 intitulé « Tentative de dictionnaire complet et critique de la grammaire de la langue haute-allemande » eut une grande importance pour l’élaboration de la langue allemande littéraire classique.</p>
    </blockquote>
</div>    </div>
</section>

<section class="section section-important section-md text-center">
    <div class="container frame">
        <h2>Deutsch lernen , Prêt(e) à commencer ?</h2>
        <p><a class="btn btn-lg btn-white margin-top-sm" href="{% url 'Authentification:signin'%}">Créer un compte</a></p>
    </div>
</section>

    </div><!-- content -->
{% include 'footer.html'%}
</div></body></html>

Home/templates/errorpagesession.html
{% extends 'Ba.html'%}
{% load static %}

{% block besoin %}
<link rel="stylesheet" href="{% static 'outils/style.css'%}"/>
{% endblock %}

{% block body %}
    <div class="content-page-error">
        <div class="content-error-image">
            <img src="{% static 'outils/error.png'%}" alt="error-image"/>
        </div>
        <div class="content-">
                <p>{{error}}</p>
        </div>
    </div>
{% endblock %}

Home/templates/header.html
{% load static %}
<header id="header">
    <nav class="menu navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_menu" aria-expanded="false">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><div style="width:210px;" class="logo icon svg-sprite svg"><img style="width:210px;" src="{% static 'session_fichiers/logo.png'%}"/></div></a>            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="main_menu">
                <ul class="nav navbar-nav navbar-right" id="yw0">
<li><a href="{% url 'Authentification:signin'%}">Cours</a></li>
<li><a href="{% url 'Home:aboutus'%}">A propos</a></li>
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="">Informations utiles <b class="caret"></b></a>
<ul class="dropdown-menu">
<li><a href="{% url 'Home:info'%}">Histoire</a></li>
<li><a href="{% url 'Home:forum'%}">Forum</a></li>
</ul>
</li>
<li><a class="btn-sm btn-white" href="{% url 'Authentification:signin' %}">Connexion</a></li>
</ul>            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</header>