Auth/urls.py
from django.urls import path
from . import views
app_name = "Authentification"
urlpatterns = [
    path("signup",views.inscription,name = "signup"),
    path("signin",views.seconnecter,name="signin"),
    path("confirm", views.confirm, name="confirm"),
    path("disconnect",views.disconnect,name="disconnect"),
    path("recover",views.recoverPassword,name="recover"),
    path("delete",views.suprimerNotValid,name="delete"),
    path("change",views.changePassword,name="change")
]

Grammar/urls.py
from sys import path

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views

app_name = "Grammar"
urlpatterns = [
    url(r'^frage', views.grammarex, name="frage"),
    url(r'^ubung', views.ubung, name="grammar"),
    url(r'^gegenteile', views.gegenteile, name="gegenteile"),
    url(r'^bestimmte-artikel', views.bartikel, name="bestimmte artikel"),
    url(r'^register', views.test, name="register"),
    url(r'^alphabet', views.alphabet, name="alphabet"),
    url(r'^menuCours', views.menu, name="menuCours"),
    url(r'^artikel', views.artikel, name="artikel"),
    url(r'^pronomscours', views.pronoms, name="pronoms"),
    url(r'^adjektive', views.adjektive, name="adjektive"),
    url(r'^pronomsindefinis', views.pronomsindefinis, name="pronomsindefinis"),
    url(r'^pronompersonnels', views.pronompersonnels, name="pronompersonnels"),
    url(r'^adverbes', views.adverbs, name="adverbes"),
    url(r'^numeraux',views.numeraux,name="numeraux"),
    url(r'^unbestimmte-artikel',views.ua,name="unbes-art"),
    url(r'^$', views.general, name="menu")
]

germanstudies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^Auth/',include("Auth.urls",namespace="Authf"),name="Authentification"),
    url(r'^Horen/', include("Horen.urls",namespace="Horenf"),name="Horen"),
    url(r'^Lesen/', include("Lesen.urls",namespace="Lesenf"),name="Lesen"),
    url(r'^Schreiben/', include("Schreiben.urls",namespace="Schreibenf"),name="Schreiben"),
    url(r'^Grammar/', include("Grammar.urls",namespace="Grammarf"),name="Grammar"),
    url(r'^',include("Home.urls",namespace="Homef"),name="Session")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Grammar/models.py
from django.db import models

from Auth.models import Personne


class Ubung(models.Model):
    frage = models.CharField(max_length=200)
    losung = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    def __str__(self):
        return self.frage
class Reponse(models.Model):
    ubung = models.OneToOneField(Ubung, on_delete=models.CASCADE)
    pers= models.ForeignKey(Personne, on_delete=models.CASCADE,related_name='pers')
    valide = models.BooleanField(default=False)

class Essai(models.Model):
    choix = models.CharField(max_length=15)
    numf = models.ForeignKey(Ubung, on_delete=models.CASCADE)

Grammar/views.py
from builtins import print

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from Home.funktions.funktion import checkSession,getSuccess,saveSucess
from django.http import HttpResponse, HttpResponseRedirect, request
from django.shortcuts import render
from django.template import loader
from . import models
from Auth.models import Personne
from .random import generateRandom
from Grammar.models import Ubung, Essai,Reponse


def grammarex(request):
  try :
        checkSession(request)
        c = Ubung.objects.filter(type="frage")
        if request.method == "POST":
            losung = request.POST
            ubungs = []
            for frage,losung in losung.items():
                for ubung in c:
                    if ubung.frage == frage:
                        ubungs.append(Ubung.objects.get(frage = frage,type="frage"))
            if len(ubungs) == 6:
                    losung = request.POST
                    cmp = 0
                    validator = {}
                    reponsejuste = {}
                    erreurfausse = {}
                    msg = ""
                    personne = Personne.objects.get(username = request.session['username'])
                    for ubung in ubungs:
                       try:
                            if str(losung[ubung.frage]) == str(ubung.losung):
                                reponse = Reponse(ubung=ubung, valide=True, pers=personne)
                                reponse.save()
                                cmp += 1
                                validator[ubung.frage] = True
                                reponsejuste[ubung.frage] = losung[ubung.frage]
                                msg = "le nombre de question Juste est ", cmp
                            else:
                                validator[ubung.frage] = False
                                erreurfausse[ubung.frage] = losung[ubung.frage]
                                reponsejuste[ubung.frage] = ubung.losung
                       except :
                            context = {
                                "error": "Veuillez selectionner tous les choix "
                            }
                            return render(request, "Grammar/errorpage.html", context)
                    saveSucess('succes_grammar',getSuccess('succes_grammar',request) + cmp,request)
                    dic = {
                    }

                    list = []
                    for ubung in ubungs:
                        list.append(ubung.losung)
                        moglichkeit = Essai.objects.filter(numf=ubung)
                        for mog in moglichkeit:
                            if mog.numf == ubung:
                                list.append(mog.choix)
                        dic[str(ubung.frage)] = list
                        list = []

                    context = {
                        'ubungs': ubungs,
                        'dictionnaire': dic,
                        'erreurs': erreurfausse,
                        'reponses':reponsejuste,
                        'validator':validator,
                        'message': msg
                    }
                    return render(request, 'Grammar/index.html', context)
            else:
                context = {
                    "error": "Veuillez selectionner tous les choix "
                }
                return render(request, "Grammar/errorpage.html", context)

        else:
            ubungse = Ubung.objects.filter(type="frage")
            personne = Personne.objects.get(username = request.session['username'])
            ubungs = []
            for ubung in ubungse:
                reponse = Reponse.objects.filter(ubung=ubung,pers=personne)
                if len(reponse) == 0:
                    ubungs.append(ubung)
            if len(ubungs) != 0:
                    dic = {
                    }
                    i = 1
                    list = []
                    paginator=Paginator(ubungs,6)
                    page=request.GET.get('page')
                    try:
                        exe = paginator.page(page)
                    except PageNotAnInteger:
                        page = 1
                        exe = paginator.page(1)
                    except EmptyPage:
                        page = 1
                        exe= paginator.page(paginator.num_pages)

                    for ubung in ubungs:
                        moglichkeit = Essai.objects.filter(numf=ubung)
                        for mog in moglichkeit:
                            if mog.numf == ubung:
                                list.append(mog.choix)
                        list.insert(generateRandom(),ubung.losung)
                        dic[str(ubung.frage)] = list
                        list = []
                    jo = {}
                    for ubung in paginator.page(page).object_list:
                        jo[ubung.frage] = dic[str(ubung.frage)]

                    print(dic)
                    context = {
                        'ubungs': ubungs,
                        'paginator': True,
                        'messages': exe,
                        'dictionnaire': jo
                    }
                    return render(request, 'Grammar/index.html', context)
            else:
                return render(request, "Grammar/sucess.html")
  except:
        return HttpResponseRedirect('/')

def ubung(request):
   try :
    checkSession(request)
    return render(request, 'Grammar/menuubungs.html')
   except :
    return HttpResponseRedirect('/')

def gegenteile(request):
  try :
    checkSession(request)
    c = Ubung.objects.filter(type="gegen")
    if request.method == "POST":
        losung = request.POST
        ubungs = []
        for frage, losung in losung.items():
            for ubung in c:
                if ubung.frage == frage:
                    ubungs.append(Ubung.objects.get(frage=frage, type="gegen"))
        if len(ubungs) == 6:
                losung = request.POST
                cmp = 0
                validator = {}
                reponsejuste = {}
                erreurfausse = {}
                msg = "le nombre de question Juste est ", 0
                personne = Personne.objects.get(username=request.session['username'])
                for ubung in ubungs:
                    reponse = Reponse(ubung=ubung, valide=True, pers=personne)
                    reponse.save()
                    if str(losung[ubung.frage]) == str(ubung.losung):
                        cmp += 1
                        validator[ubung.frage] = True
                        reponsejuste[ubung.frage] = losung[ubung.frage]
                        msg = "le nombre de question Juste est ", cmp
                    else:
                        validator[ubung.frage] = False
                        erreurfausse[ubung.frage] = losung[ubung.frage]
                        reponsejuste[ubung.frage] = ubung.losung
                saveSucess('succes_grammar', getSuccess('succes_grammar', request) + cmp, request)
                dic = {
                }

                list = []
                for ubung in ubungs:
                    list.append(ubung.losung)
                    moglichkeit = Essai.objects.filter(numf=ubung)
                    for mog in moglichkeit:
                        if mog.numf == ubung:
                            list.append(mog.choix)
                    dic[str(ubung.frage)] = list
                    list = []

                context = {
                    'ubungs': ubungs,
                    'paginator': True,

                    'dictionnaire': dic,
                    'erreurs': erreurfausse,
                    'reponses': reponsejuste,
                    'validator': validator,
                    'message': msg
                }
                return render(request, 'Grammar/index.html', context)
        else:
            context = {
                "error": "Veuillez selectionner tous les choix "
            }
            return render(request, "Grammar/errorpage.html", context)

    else:
        ubungse = Ubung.objects.filter(type="gegen")
        personne = Personne.objects.get(username=request.session['username'])
        ubungs = []
        for ubung in ubungse:
            reponse = Reponse.objects.filter(ubung=ubung, pers=personne)
            if len(reponse) == 0:
                ubungs.append(ubung)
        if len(ubungs) != 0:
            dic = {
            }
            i = 1
            list = []
            paginator = Paginator(ubungs, 6)
            page = request.GET.get('page')
            try:
                exe = paginator.page(page)
            except PageNotAnInteger:
                page = 1
                exe = paginator.page(1)
            except EmptyPage:
                page = 1
                exe = paginator.page(paginator.num_pages)

            for ubung in ubungs:
                moglichkeit = Essai.objects.filter(numf=ubung)
                for mog in moglichkeit:
                    if mog.numf == ubung:
                        list.append(mog.choix)
                list.insert(generateRandom(), ubung.losung)
                dic[str(ubung.frage)] = list
                list = []
            jo = {}
            for ubung in paginator.page(page).object_list:
                jo[ubung.frage] = dic[str(ubung.frage)]

            print(dic)
            context = {
                'ubungs': ubungs,
                'paginator': True,
                'messages': exe,
                'dictionnaire': jo
            }
            return render(request, 'Grammar/index.html', context)
        else:
            return render(request, "Grammar/sucess.html")
  except :
     return HttpResponseRedirect('/')
def bartikel(request):
  try :
    checkSession(request)
    c = Ubung.objects.filter(type="ba")
    if request.method == "POST":
        losung = request.POST
        ubungs = []

Grammar/templates/Grammar/gegenteile.html
{% extends 'Ba.html'%}
{% load static %}

{% block body %}
<link href="{% static 'css/indexo.css'%}" rel="stylesheet">
<style>
    .alignement{
        display:flex;
        flex-direction:row;
    }
    .image img{
        height:20px;
        width:20px;
    }
</style>
 <div class="general">
     <h1> APPRENDRE LA LANGUE ALLEMANDE EN UN SEUL CLIC  </h1>
     <button><a class="retour" href="{% url 'Grammar:grammar'%}"> << Alle Ubungen</a></button>

     <div>
         {% if validator == None %}
            <form method="post" action="/Grammar/gegenteile">
                {% csrf_token %}
            {% for key,values in dictionnaire.items %}
                <h3> AUFGABE {{forloop.counter}} :</h3>

              <p class="enonce">
                  <!-- affichagge du key qui represente la question -->
                  {{ key }}
              </p>
                <div class="aufgabes">
                    {% for mo in values %}
                        <!-- 'values' represente  les choix possibles -->
                       <input type="radio" name="{{ key }}" value="{{mo}}" id="{{mo}}"  >
                       <label for="{{mo}}">{{mo}}</label><br/>

                    {% endfor %}
                </div>

            {% endfor %}


                <span class="submit"><input type="submit" value="VALIDER" ></span><br/>
                <span id="msg">{{message}}</span>

            </form>
          <nav class="text-center content-item"><div class="pagination"><ul id="yw11" class="yiiPager">
    {% if messages.has_previous %}
        <li class="previous"><a href="{% url 'Grammar:gegenteile'%}?page={{messages.previous_page_number}}">Page Suivante</a></li>
    {% endif %}
    {% if messages.has_next%}
        <li class="next"><a href="{% url 'Grammar:gegenteile'%}?page={{messages.next_page_number}}">Page Precedente</a></li>
    {% endif %}
         {% else %}
            {% for key,values in dictionnaire.items %}
                <h2> AUFGABE {{forloop.counter}} :</h2>

              <p class="enonce">
                  {{ key }}

              </p>
                <div class="aufgabes">

                        {% for mo in values %}
                        <div class="alignement">
                           {% if validator.key %}
                            <!-- rep correcte -->
                                {% for keyo, value in reponses.items %}
                            <!-- rponses est un dic stockant les questions ss-frme clee et la val associe est la reponse  -->
                                    {% if mo == value and key == keyo %}
                            <!-- verification du question si elle est la mm car key est ubung.frage pr 'validator ' et auussi pr keyo  -->
                                        <div class="image">
                                            <img src="{% static 'outils/success.png'%}" alt="sss"/>
                                        </div>
                                    {% endif %}
                                        <div class="google">
                                            <input type="radio" name="{{ key }}" value="{{mo}}" id="{{mo}}2"  >
                                            <label for="{{mo}}2">{{mo}}</label><br/>
                                        </div>
                                {% endfor %}

                           {% else %}
                            <!-- rep fausse -->
                                {% for keyo, value in erreurs.items %}
                                  <!-- affichage du rep fausse -->
                                    {% if mo == value and key == keyo%}
                                           <div class="image">
                                                <img src="{% static 'css/wrong.png'%}" alt="sss"/>
                                           </div>
                                    {% endif %}
                                {% endfor %}
                                {% for keyo, value in reponses.items %}
                                  <!-- affichage du rep juste -->
                                        {% if mo == value and key == keyo %}
                                            <div class="image">
                                                <img src="{% static 'outils/success.png'%}" alt="sss"/>
                                            </div>
                                        {% endif %}
                                {% endfor %}
                                <div class="google">
                                            <input type="radio" name="{{ key }}" value="{{mo}}" id="{{mo}}1"  >
                                            <label for="{{mo}}1">{{mo}}</label><br/>
                                </div>

                           {% endif %}
                            </div>
                        {% endfor %}


                </div>

            {% endfor %}
                <p>{{message}}</p>
         {%endif%}

        </div>
 </div>
{% endblock %}

Grammar/templates/Grammar/general.html
{% extends 'Ba.html'%}
{% load static %}

{% block body %}

  <link href="./assets/favicon.ico" rel="icon">
<link href="{% static 'css/gg.css' %}" rel="stylesheet">
<div class="container">
	<button type="button" class="navbar-toggle collapsed"
		data-toggle="collapse" data-target="#navbar-collapse"
		aria-expanded="false">
		<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
		<span class="icon-bar"></span> <span class="icon-bar"></span>
	</button>


</div>


<div class="section-container">
	<div class="container">
		<div class="row">

			<div class="col-sm-8 col-sm-offset-2 section-container-spacer">
				<div class="text-center">
					<h1 class="h1"> GRAMMAR</h1>
					<p>Pour parler et écrire correctement l’allemand, il est important de connaître les principales règles de grammaire et certains termes techniques. Nos explications ont été conçues pour que
						tu puisses les apprendre facilement et faire des progrès rapides. Tous les points
						essentiels sont résumés de manière simple et claire. Les exercices te permettent d’appliquer et de conforter
						tout de suite tes nouvelles connaissances</p>
				</div>
			</div>

			<div class="col-md-12">

				<div id="myCarousel" class="carousel slide projects-carousel">
					<!-- Carousel items -->
					<div class="carousel-inner">
						<div class="item active">
							<div class="row">
								<div class="col-sm-4">

									<a href="{% url 'Grammar:menuCours' %}" title=""
										class="black-image-project-hover"> <img
										src="{% static 'work01-hover.jpg' %}" alt=""
										class="img-responsive">
									</a>
									<div class="card-container card-container-lg">
										<h4>001</h4>
										<h3>COURS</h3>
										<p>Vous souhaitez apprendre l’allemand ou simplement réviser vos acquis, améliorer
											vos connaissances ou approfondir le sujet ? Venez testez notre site en ligne spécialisé  pour les étudiants souhaitant apprendre la langue
											et n’ayant aucune base</p>
										<a href="{% url 'Grammar:menuCours' %}" title="" class="btn btn-default">Discover</a>
									</div>
								</div>
								<div class="col-sm-4">
									<a href="./work.html" title=""
										class="black-image-project-hover"> <img
										src="{% static 'work001-04.jpg' %}" alt=""
										class="img-responsive">
									</a>
									<div class="card-container card-container-lg">
										<h4>002</h4>
										<h3>EXERCICES</h3>
										<p>Exercices d'allemand pour les débutants
											et tous ceux qui souhaitent améliorer leurs connaissances de la langue allemande en ligne et gratuitement
										 Testez notre site en ligne spécialisé  pour les étudiants souhaitant exercicer la langue
											et n’ayant aucune base
										</p>
										<a href="{% url 'Grammar:grammar' %}" title="" class="btn btn-default">Discover</a>
									</div>
								</div>
								<div class="col-sm-4">
									<a href="" title=""
										class="black-image-project-hover"> <img
										src="{% static 'work001-03.jpg' %}" alt=""
										class="img-responsive">
									</a>
									<div class="card-container card-container-lg">
										<h4>003</h4>
										<h3>L'ALLEMAND AUTREMENT</h3>
										<p> quizz et jeux pour vous divertir en approfondissant vos connaissances
											de la civilisation des pays de langue allemande</p>
										<P style="color :red ;font-family:serif ;font-size :medium;">Comming soon</P>
										<a href="" title="" class="btn btn-default">Pardon</a>
									</div>
								</div>

							</div>

						</div>
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Grammar/templates/Grammar/menuubungs.html
{% extends 'Ba.html'%}
{% load static%}
{% block body%}
<link href="{% static 'css/menuu.css'%}" rel="stylesheet">
<div class="general">
    <h1><span id="deustch">Deutsch</span> <span id="ubungen">Übungen</span></h1>
     <button><a class="retour" href="/Grammar"> << MENU</a></button>
    <div class="firstp">
                    <a><img src="{%static 'lehrer.jpg'%}" class="photo"></a>
                    <p class="content_text">Deutsch Übungen für Anfänger, Fortgeschrittene und alle, die online und
                    kostenlos ihre Kenntnisse der deutschen Sprache verbessern möchten.</p>
                    <p>
                    Die Aufgaben richten sich nicht nur an Sprachschüler, die die deutsche
                    Sprache lernen möchten, aber auch an Schüler, die nach zusätzlichem
                    Material zum Üben suchen. Besonders für Ausländer ist die deutsche
                    Sprache mit ihrer anspruchsvollen Grammatik eine Herausforderung. Bei
                    uns gibt es im Speziellen Material für Themen, die vielen Schülern
                    Schwierigkeiten bereiten – z.B. die korrekte Verwendung der Artikel,
                    Adjektive, Pronomen, Zeiten und der Umgang mit den vier Fällen
                    (Nominativ, Genitiv, Akkusativ und Dativ).</p>
                    <p>Fall alleOnline-Übungen bestehen aus Multiple-Choice-Fragen. Die ideale Methode
                    für daheim am PC und unterwegs auf dem Smartphone: Einfach eine Antwort
                    auswählen und direkt die Lösung sehen. Zusätzlich wird jede Übung als
                    Arbeitsblatt im PDF-Format zum Downloaden und Drucken angeboten. Ideal
                    als zusätzliche Hausaufgaben oder als Unterrichtsmaterial für Lehrer.</p>
            </div>

        <div class="panel" id="exercises" style="padding:0; padding-top:20px; clear:both">

                 <h2 class="content-h2">Niveau A1</h2>
                <div class="content_left content_text_left">
                    <table style="width:100%">
                            <tbody>
                                <tr>
                                    <th>Name</th>
                                    <th style="padding-right:10px;text-align:center"></th>
                                    <th class="hide360"></th>
                                    <th class="hide420" style="padding-left:10px">PDF</th>
                                </tr>
                                <tr>
                                    <td class="first-td"><a href="{% url 'Grammar:frage'%}" class="reading-link">Fragewörter für Anfänger</a><br>
                                        <span style="font-size:0.85em; color:#474747; display:block;">Fragepronomen und -Adverbien unterscheiden</span>
                                    </td>
                                    <td style="text-align:center; padding-right:10px; width:42px; font-size:0.9em; vertical-align:middle">
                                        <span class="button-stats button-stats-table button-stats-pale" title="Bisher noch nicht getestet"></span></td>
                                    <td class="hide360" style="vertical-align:middle;"><a href="" class="button" style="margin:0"></a></td>
                                    <td class="hide420" style="vertical-align:middle; border-left:1px solid #E8E8E8; padding-left:10px;">
                                      <a href="{% static 'css/output.pdf'%}" target="_blank"><img src="{%  static 'css/pdf.gif'%}" alt="PDF" style="width:25px; height:auto; margin:0px; vertical-align:middle; display:inline-block;"></a></a>
                                    </td></tr>
                                    <tr><td class="first-td"><a href="{% url 'Grammar:gegenteile'%}" class="reading-link">Adjektive und ihre Gegenteile</a>
                                         <br><span style="font-size:0.85em; color:#474747; display:block;">Welches Adjektiv hat die gegenteilige Bedeutung?</span>
                                    </td>
                                        <td style="text-align:center; padding-right:10px; width:42px; font-size:0.9em; vertical-align:middle"><span class="button-stats button-stats-table button-stats-pale" title="Bisher noch nicht getestet"></span></td>
                                        <td class="hide360" style="vertical-align:middle;"><a href="" class="button" style="margin:0"></a></td>
                                        <td class="hide420" style="vertical-align:middle; border-left:1px solid #E8E8E8; padding-left:10px;"><a href="{% static 'css/output2.pdf'%}" target="_blank"><img src="{%  static 'css/pdf.gif'%}" alt="PDF" style="width:25px; height:auto; margin:0px; vertical-align:middle; display:inline-block;"></a></td>
                                    </tr>
                            </tbody>
                    </table>
                </div>
            <div class="content_right content_text_right">
                    <table style=" width:100%">
                        <tbody>

                        <tr>
                            <td class="first-td"><a href="{% url 'Grammar:bestimmte artikel'%}" class="reading-link">Bestimmte Artikel</a><br>
                                <span style="font-size:0.85em; color:#474747; display:block;">Lerne die Artikel häufig genutzter Nomen</span></td>
                            <td style="text-align:center; padding-right:10px; width:42px; font-size:0.9em; vertical-align:middle"><span class="button-stats button-stats-table button-stats-pale" title="Bisher noch nicht getestet"></span></td>
                            <td class="hide360" style="vertical-align:middle;"><a href="" class="button" style="margin:0"></a></td>
                            <td class="hide420" style="vertical-align:middle; border-left:1px solid #E8E8E8; "><a href="{% static 'css/output.pdf'%}"target="_blank"><img src="{%  static 'css/pdf.gif'%}" alt="PDF" style="width:25px; height:auto; margin:0px; vertical-align:middle; display:inline-block;"></a>
                            </td>
                        </tr>
                        <tr>
                            <td class="first-td"><a href="{%  url 'Grammar:unbes-art' %}" class="reading-link">Unbestimmte Artikel</a><br>
                                <span style="font-size:0.85em; color:#474747; display:block;">Welche sind die richtigen unbestimmten Artikel?</span>
                            </td>
                            <td style="text-align:center;  width:42px; font-size:0.9em; vertical-align:middle"><span class="button-stats button-stats-table button-stats-pale" title="Bisher noch nicht getestet"></span></td>
                            <td class="hide360" style="vertical-align:middle;"><a href="" class="button" style="margin:0"></a></td>
                            <td class="hide420" style="vertical-align:middle; border-left:1px solid #E8E8E8; "></td>
                        </tr>
                        </tbody>
                    </table>
            </div>
        </div>
  </div>
{% endblock %}

Grammar/templates/Grammar/pronoms.html
{% extends 'Ba.html' %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="">
<div id="content">
	<h1>Les déterminants et pronoms allemands</h1>
	<button><a class="retour" href="{% url 'Grammar:menuCours'%}"> << MENU</a></button>
	<section class="mod_article first last block" id="les-pronoms">
		<div class="ce_text first block">
			<h2 id="a-introduction">Introduction</h2>
			<p>
				La fonction des <b>pronoms</b> est de remplacer un nom. En allemand, les pronoms se
				déclinent. Quant aux <b>déterminants</b><span>, ils
					accompagnent un <span class="glossary" data-term="420">nom</span>
					en apportant une nuance de sens.
				</span>
			</p>
			<p>En allemand comme en français, il existe des pronoms
				personnels, des déterminants et pronoms possessifs, des pronoms
				réfléchis, des pronoms relatifs, des pronoms interrogatifs, des
				pronoms indéfinis, des déterminants et pronoms démonstratifs.</p>
			<p>
				<span>En cliquant sur le type de déterminants/pronoms de ton
					choix, tu pourras en apprendre plus sur sa définition, son emploi
					et la <span class="glossary" data-term="347">déclinaison</span> qui
					lui correspond. Teste ensuite tes nouvelles connaissances avec nos
					exercices&nbsp;!
				</span>
			</p>
		</div>
		<div class="sc-container">
			<div class="sc-col sc-col-lg-2-1 sc-col-sm-1-1">
				<div class="ce_page_teaser ce_teaser_link block"
					data-url="fr/grammaire/les-pronoms/pronoms-personnels">
					<h2 id="a-les-pronoms-personnels">
						<a
							href="{%url 'Grammar:pronompersonnels' %}"
							title="Les pronoms personnels allemands">Les pronoms
							personnels</a>
					</h2>
					<p>
						Les pronoms personnels sont <em>ich, du, er, sie, es, wir,
							ihr, sie</em> et leurs formes déclinées<em>.</em> Les pronoms
						personnels remplacent un nom habituellement déjà mentionné.
					</p>
				</div>
			</div>

			<div class="sc-col sc-col-lg-2-1 sc-col-sm-1-1">
				<div class="ce_page_teaser ce_teaser_link block"
					data-url="fr/grammaire/les-pronoms/pronoms-indefinis">
					<h2 id="a-les-pronoms-indefinis">
						<a
							href="{% url 'Grammar:pronomsindefinis'%}"
							title="Les pronoms indéfinis allemands">Les pronoms indéfinis</a>
					</h2>
					<p>
						Les pronoms indéfinis allemands sont par exemple <em>etwas,
							nichts, man, jemand, niemand, jeder</em>. Ils désignent quelque chose
						ou quelqu’un de façon générale ou indéterminée.
					</p>
				</div>
			</div>

		</div>
	</section>
</div>
{% endblock %}